### PR TITLE
Added html-title and html-details inputs. 

### PR DESCRIPTION
**Pull request by niwciu**
Added two new inputs:
-  `html-details` - an option to add annotated source code reports to the HTML report.  By default, it's set to `false`
- `html-title` - option for changing the default report title in the generated HTML document

### CODE REVIEW

**Comment by niwciu** [comment]
Hi, 
I hope you don't mind making those small changes in your code. 
From my point of view, I would like to have this functionality in my embedded project automation, but I prefer to add this small peace and use officially your action rather than work on a copy of your project with those changes. Especially since I'm also doing some trainings for embedded engineers, so again I would like to show your work rather than a copy of it, with small changes in my repo.

BTW when you are planning to relese 1.1.0 ?

**Comment by threeal** [comment]
Nah, it's fine. I think in the future we should also support all arguments available in the `gcovr` command as action inputs.

I'm actually planning to release this in v2.0.0, but it's still a long road ahead as I need to release the dependency for this action first and replacing some other dependencies.

But if you're done with all the changes, i can release it as version 1.1.0 first.

**Review by threeal — COMMENTED** [review]
Code looks good. However, can you rebase the commits first?

Even though we use squash commits in this project, the commit description will include a list of all the squashed commits. Can you rebase the commits and remove any that are not related to this pull request first?

**Comment by niwciu** [comment]
I will clean up the forked repo main branch and create a new PR where changes added in this PR will be added + any other that will be needed from my side. So if it's not a problem to make a release of v1.1.0 I will let you know about this in the comments of the next PR. 
I need to double-check all my gcovr targets in projects on the local machine to confirm that added inputs cover all current needs. Due the fact that it's not my professional work probably I will be able to do this soonest during the weekend.

**Pull request closed without merging**
